# Generated by Django 5.0.4 on 2024-04-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.PositiveIntegerField(default=0)),
                ('num2', models.PositiveIntegerField(default=0)),
                ('sum', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('FAILED', 'FAILED'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=100)),
            ],
        ),
    ]
